name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: 1.0.0 # <<--- Define the version HERE --->>
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: Build Docker
        run: docker build -t ghcr.io/${{ github.repository_owner }}/friendsandplaces:${{ env.DOCKER_TAG }} .

      - name: Push Docker to ghcr
        run: docker push ghcr.io/${{ github.repository_owner }}/friendsandplaces:${{ env.DOCKER_TAG }}