name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: python -m UnitTests.StartAll

  build_docker:
      runs-on: self-hosted
      needs: test
      env:
        DOCKER_TAG: 1.0.0 # <<--- Define the version HERE --->>

      steps:
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: Build Docker
        run: docker build -t ghcr.io/jackson085/art_shop:${{ env.DOCKER_TAG }} .

      - name: Push Docker to ghcr
        run: docker push ghcr.io/jackson085/art_shop:${{ env.DOCKER_TAG }}