name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  build_docker:
    runs-on: self-hosted
    needs: test
    env:
      DOCKER_TAG: 1.0.0 # <<--- Define the version HERE --->>
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: Build Docker
        run: docker build -t ghcr.io/${{ github.repository_owner }}/friendsandplaces:${{ env.DOCKER_TAG }} .

      - name: Push Docker to ghcr
        run: docker push ghcr.io/${{ github.repository_owner }}/friendsandplaces:${{ env.DOCKER_TAG }}